### PR TITLE
fix(aboutPage) use https and remove <object>

### PR DESCRIPTION
**Pull request by florent1933**
working on Chrome now. Image wasn't displaying.

### CODE REVIEW

**Comment by aubincleme** [comment]
Hi @florent1933. 
Thanks for taking care of this project health after such a long time !

Unfortunately, the root git repository of this project is located [here](https://gitlab.atilla.org/atilla/atilla). As mentioned [here](https://gitlab.atilla.org), you can request an account to the GitLab instance simply by writing a mail to admins [at] lists [dot] atilla [dot] org. When that’s done, you should be able to create a merge request on the root project.

If you don’t want to spend such time requesting a new account / creating a merge request on [gitlab.atilla.org](https://gitlab.atilla.org), I can forward your commit to the current project owner, @jordankevi.

**Review by aubincleme — CHANGES_REQUESTED** [review]
Pull request should be forwarded to https://gitlab.atilla.org/atilla/atilla.

**Comment by florent1933** [comment]
Thanks @aubincleme, please forward it to @jordankevi :)

**Comment by aubincleme** [comment]
I created a corresponding merge request [here](https://gitlab.atilla.org/atilla/atilla/merge_requests/11).
Thanks again !

**Pull request closed without merging**
